dir_in = "C:/Users/lab/Desktop/temp/Oficio N° 966-2022/datos"
file_extension = ".wav"
target_extension = ".TextGrid"
repository_dir = "C:/Users/lab/OneDrive/Documents/OPERIT/casos-transcripción/trn_021/scripts/.data/transcription-repository"
dynamic_mode = false
overwrite_mode = false
